DROP TABLE IF EXISTS Customer;
CREATE TABLE Customer
(
 Username VARCHAR(30) NOT NULL,
 Fname VARCHAR(20) NOT NULL,
 Lname VARCHAR(20) NOT NULL,
 Street VARCHAR(50),
 City VARCHAR(50),
 State VARCHAR(20),
 Zipcode MEDIUMINT(5) ZEROFILL,
 Phone VARCHAR(15),
 Email VARCHAR(50),
 PRIMARY KEY (Username)
) ENGINE=InnoDB CHARACTER SET=utf8;

DROP TABLE IF EXISTS Warranty;
CREATE TABLE Warranty
(
 WarrantyID INT NOT NULL AUTO_INCREMENT,
 Type VARCHAR(20) NOT NULL,
 PRIMARY KEY (WarrantyID)
) ENGINE=InnoDB CHARACTER SET=utf8;

DROP TABLE IF EXISTS WHouse;
CREATE TABLE WHouse
(
 WHouseID INT NOT NULL AUTO_INCREMENT,
 Street VARCHAR(50) NOT NULL,
 City VARCHAR(50) NOT NULL,
 State VARCHAR(20) NOT NULL,
 Zipcode MEDIUMINT(5) ZEROFILL NOT NULL,
 PRIMARY KEY (WHouseID)
) ENGINE=InnoDB CHARACTER SET=utf8;

DROP TABLE IF EXISTS `Server`;
CREATE TABLE `Server`
(
 ServerID INT NOT NULL AUTO_INCREMENT,
 SvLocation VARCHAR(20) NOT NULL,
 PRIMARY KEY (ServerID)
) ENGINE=InnoDB CHARACTER SET=utf8;

DROP TABLE IF EXISTS Store;
CREATE TABLE Store
(
 URL VARCHAR(50) NOT NULL,
 StoreID INT NOT NULL AUTO_INCREMENT,
 WHouseID INT NOT NULL,
 ServerID INT NOT NULL,
 PRIMARY KEY (StoreID),
 FOREIGN KEY (WHouseID) REFERENCES WHouse(WHouseID) ON UPDATE CASCADE,
 FOREIGN KEY (ServerID) REFERENCES `Server`(ServerID) ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET=utf8;

DROP TABLE IF EXISTS Supplier;
CREATE TABLE Supplier
(
 SupplierID INT NOT NULL AUTO_INCREMENT,
 SName VARCHAR(20) NOT NULL,
 SInfo VARCHAR(20),
 Street VARCHAR(50),
 City VARCHAR(50) ,
 State VARCHAR(20),
 Zipcode MEDIUMINT(5) ZEROFILL,
 PRIMARY KEY (SupplierID)
) ENGINE=InnoDB CHARACTER SET=utf8;

DROP TABLE IF EXISTS Category;
CREATE TABLE Category
(
 CatID VARCHAR(50) NOT NULL,
 PRIMARY KEY (CatID)
) ENGINE=InnoDB CHARACTER SET=utf8;

DROP TABLE IF EXISTS Orders;
CREATE TABLE Orders
(
 OrderID INT NOT NULL AUTO_INCREMENT,
 OrderTime DATETIME NOT NULL,
 Cost DECIMAL(10,2) NOT NULL,
 EDDate DATETIME NOT NULL,
 SDate DATETIME NOT NULL,
 DDate DATETIME NOT NULL,
 Shipped BOOLEAN NOT NULL,
 Delivered BOOLEAN NOT NULL,
 Street VARCHAR(50),
 City VARCHAR(50),
 State VARCHAR(20),
 Zipcode MEDIUMINT(5) ZEROFILL,
 Username VARCHAR(30) NOT NULL,
 StoreID INT NOT NULL,
 PRIMARY KEY (OrderID),
 FOREIGN KEY (Username) REFERENCES Customer(Username) ON UPDATE CASCADE,
 FOREIGN KEY (StoreID) REFERENCES Store(StoreID) ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET=utf8;

DROP TABLE IF EXISTS SubCategory;
CREATE TABLE SubCategory
(
 SubCatID VARCHAR(50) NOT NULL,
 CatID VARCHAR(50) NOT NULL,
 PRIMARY KEY (SubCatID),
 FOREIGN KEY (CatID) REFERENCES Category(CatID) ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET=utf8;


DROP TABLE IF EXISTS Part;
CREATE TABLE Part
(
 PartNo VARCHAR(10) NOT NULL,
 Pname VARCHAR(50) NOT NULL,
 PCompany VARCHAR(50) NOT NULL,
 PImage VARCHAR(50) DEFAULT 'default.jpg',
 Price DECIMAL(10,2) NOT NULL,
 SubCatID VARCHAR(50) NOT NULL,
 WarrantyID INT NOT NULL,
 PRIMARY KEY (PartNo),
 FOREIGN KEY (SubCatID) REFERENCES SubCategory(SubCatID) ON UPDATE CASCADE,
 FOREIGN KEY (WarrantyID) REFERENCES Warranty(WarrantyID) ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET=utf8;

DROP TABLE IF EXISTS Supplies;
CREATE TABLE Supplies
(
 SupplyDate DATETIME NOT NULL,
 SpQuantity INT NOT NULL,
 SupplierID INT NOT NULL,
 PartNo VARCHAR(10) NOT NULL,
 PRIMARY KEY (SupplyDate, SupplierID, PartNo),
 FOREIGN KEY (SupplierID) REFERENCES Supplier(SupplierID) ON UPDATE CASCADE,
 FOREIGN KEY (PartNo) REFERENCES Part(PartNo) ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET=utf8;

DROP TABLE IF EXISTS SInventory;
CREATE TABLE SInventory
(
 StQuantity INT NOT NULL,
 StoreID INT NOT NULL,
 PartNo VARCHAR(10) NOT NULL,
 PRIMARY KEY (StoreID, PartNo),
 FOREIGN KEY (StoreID) REFERENCES Store(StoreID) ON UPDATE CASCADE,
 FOREIGN KEY (PartNo) REFERENCES Part(PartNo) ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET=utf8;

DROP TABLE IF EXISTS CarInfo;
CREATE TABLE CarInfo
(
 Make VARCHAR(30) NOT NULL,
 Model VARCHAR(30) NOT NULL,
 MinYear YEAR(4) NOT NULL,
 MaxYear YEAR(4) NOT NULL,
 PartNo VARCHAR(10) NOT NULL,
 PRIMARY KEY (Make, Model, MinYear, MaxYear, PartNo),
 FOREIGN KEY (PartNo) REFERENCES Part(PartNo) ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET=utf8;

DROP TABLE IF EXISTS OInventory;
CREATE TABLE OInventory
(
 OrQuantity INT NOT NULL,
 OrderID INT NOT NULL,
 PartNo VARCHAR(10) NOT NULL,
 PRIMARY KEY (OrderID, PartNo),
 FOREIGN KEY (OrderID) REFERENCES Orders(OrderID) ON UPDATE CASCADE,
 FOREIGN KEY (PartNo) REFERENCES Part(PartNo) ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET=utf8;

DROP TABLE IF EXISTS Users;
CREATE TABLE Users
(
 Username VARCHAR(30) NOT NULL,
 Password VARCHAR(16) NOT NULL,
 Admin BOOLEAN NOT NULL DEFAULT False,
 PRIMARY KEY (Username),
 FOREIGN KEY (Username) REFERENCES Customer(Username) ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET=utf8;

DROP TABLE IF EXISTS UserCart;
CREATE TABLE UserCart
(
 PartNo VARCHAR(10) NOT NULL,
 Username VARCHAR(30) NOT NULL,
 PartQuantity INT NOT NULL,
 PRIMARY KEY (PartNo, Username),
 FOREIGN KEY (PartNo) REFERENCES Part(PartNo) ON UPDATE CASCADE,
 FOREIGN KEY (Username) REFERENCES Customer(Username) ON UPDATE CASCADE 
) ENGINE=InnoDB CHARACTER SET=utf8;